pom.xml

Need to assign phases to the node/npm install and bower install goals so that these occur prior to the less source being compiled.

Setup cleanup

---

bower.json
src/main/webapp/dataDiscovery.jsp
src/main/webapp/js/hb_templates/dataDiscovery.hbs
src/main/webapp/js/hb_templates/workflowNav.hbs
src/main/webapp/js/views/DataDiscoveryView.js
src/main/webapp/js/views/NavView.js
src/main/webapp/less/custom.less
src/main/webapp/less/dataDiscovery.less
src/main/webapp/less/workflowNav.less
src/test/js/karma.conf.js
src/test/js/test-main.js
src/test/js/views/DataDiscoveryViewSpec.js

The NavView will need to have more functionality eventually to do things like set the state of the buttons, click handlers, etc. Right now there is nothing to test in there so I didn't add any tests.
I also am defining less files to go along with the handlebars templates. Not sure if I like this yet, but that is the direction I'm taking at the moment.

Enddat 134

---

bower.json
package.json
src/main/webapp/dataDiscovery.jsp
src/main/webapp/js/controller/AppRouter.js
src/main/webapp/js/hb_templates/dataDiscovery.hbs
src/main/webapp/js/views/DataDiscoveryView.js
src/main/webapp/js/views/MapView.js
src/main/webapp/js/views/NavView.js
src/main/webapp/less/custom.less
src/main/webapp/less/dataDiscovery.less
src/test/js/karma.conf.js
src/test/js/test-main.js
src/test/js/views/DataDiscoveryViewSpec.js
src/test/js/views/MapViewSpec.js

Brought in Leaflet and Leaflet.Providers to implement the map and base layers. Added a MapView which will create a map with base layers and a layer switcher control. Added tests
Brought in the karma-sinon framework and removed the sinon dependency from bower.json.
Reformatted bower.json and karma.conf.js to use tabs.

Enddat 135

---

bower.json
src/main/webapp/dataDiscovery.jsp
src/main/webapp/js/controller/AppRouter.js
src/main/webapp/js/hb_templates/workflowNav.hbs
src/main/webapp/js/init.js
src/main/webapp/js/models/WorkflowStateModel.js
src/main/webapp/js/views/DataDiscoveryView.js
src/main/webapp/js/views/MapView.js
src/main/webapp/js/views/NavView.js
src/main/webapp/less/workflowNav.less
src/test/js/karma.conf.js
src/test/js/test-main.js
src/test/js/views/DataDiscoveryViewSpec.js
src/test/js/views/MapViewSpec.js

Added the ability to click on a location on the map, create a marker, and save the location to a model.
As part of this ticket, I also updated the NavView extensively to start implementing the navigation. I added routes for the choose data step (although I have only tested the first). Note that the url is updated as the workflow state changes but this does not render the entire page.
I also added loglevel to provide javascript logging.

Enddat 136

---

src/main/webapp/js/hb_templates/collapsiblePanel.hbs
src/main/webapp/js/views/BaseCollapsiblePanelView.js
src/main/webapp/js/views/DataDiscoveryView.js
src/main/webapp/js/views/LocationView.js
src/main/webapp/js/views/MapView.js
src/main/webapp/less/custom.less
src/test/js/views/BaseCollapsiblePanelViewSpec.js
src/test/js/views/MapViewSpec.js

Added an opened option to BaseCollapsibleView so that when these views are instantiated the view can be rendered with the panel open or collapsed.
To make the cursor the hand pointer when first clicking on the map, you must set the .leaflet-clickable class on the tile layers and then remove it when no longer desired.
Also added the ability to update the extent when the location is changed.

Enddat 150

---

src/main/webapp/dataDiscovery.jsp
src/main/webapp/js/Config.js
src/main/webapp/js/controller/AppRouter.js
src/main/webapp/js/hb_templates/nwisData.hbs
src/main/webapp/js/hb_templates/precipData.hbs
src/main/webapp/js/models/NWISCollection.js
src/main/webapp/js/models/WorkflowStateModel.js
src/main/webapp/js/utils/LUtils.js
src/main/webapp/js/views/ChooseView.js
src/main/webapp/js/views/DataDiscoveryView.js
src/main/webapp/js/views/MapView.js
src/main/webapp/js/views/NWISDataView.js
src/main/webapp/js/views/NavView.js
src/main/webapp/js/views/PrecipDataView.js
src/main/webapp/less/custom.less
src/main/webapp/less/dataView.less
src/test/js/karma.conf.js
src/test/js/models/NWISCollectionSpec.js
src/test/js/models/WorkflowStateModelSpec.js
src/test/js/views/ChooseViewSpec.js
src/test/js/views/DataDiscoveryViewSpec.js
src/test/js/views/MapViewSpec.js
src/test/js/views/NWISDataViewSpec.js
src/test/js/views/NavViewSpec.js
src/test/js/views/PrecipDataViewSpec.js

Added the NWISDataView which is similar to PrecipDataView except it shows the available NWIS variables for a site. Also changed the name of SiteCollection (too generic) to NWISCollection.
Created a Config.js module which contains a json object with application constants. The constants that were in WorkflowStateModel are here now, so many of the changes are due to that. 
In MapView, refactored to generalize much of the code so it can be used for any dataset.

Enddat 141

---

src/main/webapp/js/Config.js
src/main/webapp/js/leafletCustomControls/legendControl.js
src/main/webapp/js/views/MapView.js
src/main/webapp/js/views/VariableSummaryView.js
src/main/webapp/less/mapOps.less
src/test/js/karma.conf.js
src/test/js/leafletCustomControls/legendControlSpec.js
src/test/js/views/MapViewSpec.js

Extended the Leaflet.Control to create a collapsible legend control. Added the dataset icons and sizes to Config. This should allow us to easily add new datasets without having to change the legend control code.

Enddat 143

---

pom.xml

Backing off the proxy-utils dependency to 1.0.9

Enddat 172

---

src/main/webapp/js/hb_templates/workflowNav.hbs
src/main/webapp/js/views/NavView.js
src/test/js/views/NavViewSpec.js

Added a warning modal when the project location button is clicked to verify that its okay to reset the state of the app.

Enddat 166

---

src/main/webapp/js/hb_templates/dataDiscovery.hbs
src/main/webapp/js/models/WorkflowStateModel.js
src/main/webapp/js/views/ChooseView.js
src/main/webapp/js/views/DataDiscoveryView.js
src/main/webapp/less/dataDiscovery.less
src/test/js/models/WorkflowStateModelSpec.js
src/test/js/views/DataDiscoveryViewSpec.js

I added additional text to the successfully loaded message to indicate what filter was used to load and display the data. Since we want this message to be updated when the date filter changes, tied event handlers to the date filter attributes which show the alert message. Also modified the dataset:updateStarted and dataset:updateFinished signals to be sent, even when no datasets are loaded but only cleared.

Enddat 173

---

src/main/webapp/js/hb_templates/processData.hbs
src/main/webapp/js/models/BaseDatasetCollection.js
src/main/webapp/js/models/BaseVariableCollection.js
src/main/webapp/js/models/WorkflowStateModel.js
src/main/webapp/js/views/ChooseView.js
src/main/webapp/js/views/ProcessDataView.js
src/test/js/models/BaseDatasetCollectionSpec.js
src/test/js/models/BaseVariableCollectionSpec.js
src/test/js/models/WorkflowStateModelSpec.js
src/test/js/views/ChooseViewSpec.js
src/test/js/views/DataDiscoveryViewSpec.js
src/test/js/views/ProcessDataViewSpec.js

Added date time pickers to the ProcessDataView. Changed the way outputDateRange is initialized in WorkflowStateModel. We now use the date range set in the choose data filter. If that is not set, then use the last month of the date range of the selected variables.

Enddat 197

---

src/main/webapp/js/hb_templates/processData.hbs
src/main/webapp/js/models/WorkflowStateModel.js
src/main/webapp/js/views/ProcessDataView.js
src/main/webapp/less/processData.less
src/test/js/models/WorkflowStateModelSpec.js
src/test/js/test-main.js
src/test/js/views/ProcessDataViewSpec.js

Added input fields to configure the processing output. Changes are pretty straightforward. Did add a couple of tests for process data url formation.

Enddat 200

---

src/main/webapp/js/models/NWISCollection.js
src/main/webapp/js/utils/rdbUtils.js
src/main/webapp/js/utils/stringUtils.js
src/test/js/utils/rdbUtilsSpec.js
src/test/js/utils/stringUtilsSpec.js

Moved toTitleCase out of rdbUtils and into a new module stringUtils. The function is not rdb specific and is a general purpose utility.
Added tests for both the new stringUtils and rdbUtils modules. Pretty straightforward.

Enddat 157

---

src/test/js/models/NWISCollectionSpec.js
src/test/js/test-main.js
src/test/js/views/VariableSummaryViewSpec.js

Added tests to NWISCollectionSpec, using the sinon.fakeServer api to fake XMLHttpRequest responses. Some of the parsing code was tested, but my main objective was to test that the responses are parsed when a good response is returned and bad responses are properly handled.

Enddat 159

---

src/main/webapp/js/hb_templates/acisData.hbs
src/main/webapp/js/hb_templates/precipData.hbs
src/main/webapp/js/models/ACISCollection.js
src/main/webapp/js/views/ACISDataView.js
src/main/webapp/js/views/BaseDataView.js
src/main/webapp/js/views/MapView.js
src/main/webapp/js/views/NWISDataView.js
src/main/webapp/js/views/PrecipDataView.js
src/main/webapp/js/views/VariableSummaryView.js
src/test/js/models/ACISCollectionSpec.js
src/test/js/views/BaseDataViewSpec.js
src/test/js/views/NWISDataViewSpec.js
src/test/js/views/PrecipDataViewSpec.js
src/test/js/views/VariableSummaryViewSpec.js

Refactored code by creating a BaseDataView which will be extended for each site collection. When extending this view, the template, panelHeading, panelBodyId, and render function will be redefined for the specific dataset. Extended this view to implement the NWISDataView, PrecipDataView and the new ACISDataView. 
Added the ACIS collection to VariableSummaryView and corrected the creation of the variableParameter for ACIS so that the process data feature works.

Enddat 189

---

src/main/webapp/js/Config.js
src/main/webapp/js/hb_templates/choose.hbs
src/main/webapp/js/hb_templates/glcfsData.hbs
src/main/webapp/js/models/GLCFSCollection.js
src/main/webapp/js/views/GLCFSDataView.js
src/main/webapp/js/views/MapView.js
src/main/webapp/js/views/VariableSummaryView.js
src/test/js/views/GLCFSDataViewSpec.js
src/test/js/views/MapViewSpec.js
src/test/js/views/VariableSummaryViewSpec.js

created for review and feedback
still needs tests

adding data view for GLCFS

---

src/main/webapp/Intro.jsp
src/main/webapp/less/custom.less
src/main/webapp/less/splash.less

Was overriding a bootstrap less variable, so switched the variable name and should be the fix.

Drop down text color fix

---

src/main/webapp/js/models/GLCFSCollection.js
src/main/webapp/js/views/VariableSummaryView.js
src/test/js/models/GLCFSCollectionSpec.js

Best available URL generation... just missing that lake param

ENDDAT-177

---

src/main/webapp/js/views/ChooseView.js

@mbucknell heres my code for the GA tracker of the selection for datasets. 
I first had it in the selectDataset function previously created, but was receiving multiple calls of the function which was reporting the selection text to google too many times causing fake data to appear.
So I created the gaSelectorTracker function, do you see any issues with that? It seems to not be messing with anything from what I've seen, but if you can see a cleaner solution I'm all ears.

GA for Dataset selection

---

src/main/webapp/js/hb_templates/processData.hbs
src/main/webapp/js/hb_templates/urlContainer.hbs
src/main/webapp/js/models/ACISCollection.js
src/main/webapp/js/models/GLCFSCollection.js
src/main/webapp/js/models/NWISCollection.js
src/main/webapp/js/models/PrecipitationCollection.js
src/main/webapp/js/utils/VariableParameter.js
src/main/webapp/js/views/ProcessDataView.js
src/test/js/utils/VariableParameterSpec.js
src/test/js/views/ProcessDataViewSpec.js

@mbucknell:
Could you give this a look and let me know what you think of the additions?

Enddat 229

---

pom.xml
src/main/webapp/Intro.jsp
src/main/webapp/WEB-INF/jsp/head.jsp
src/main/webapp/WEB-INF/web.xml
src/main/webapp/dataDiscovery.jsp
src/main/webapp/js/models/ACISCollection.js
src/main/webapp/js/models/NWISCollection.js
src/test/js/models/ACISCollectionSpec.js
src/test/js/models/NWISCollectionSpec.js
src/test/js/test-main.js

In order to serve the application as https, removed all of the absolute paths for the static resources in favor of using relative paths. All services that do not provide a reliable https service now use proxies.

Enddat 223

---

src/main/webapp/Intro.jsp

This should make the tabs work for the intro page. Right @jiwalker-usgs ?
It at least made my local version work again
or @mbucknell ?

get JQUERY path to work

---

src/main/webapp/js/views/ChooseByVariableKindView.js
src/main/webapp/json/variableDatasetMapping.json
src/test/js/views/ChooseByVariableKindViewSpec.js

Fixed a typo in retrieving the variableKinds property and added a test to test for the bad condition.

Enddat 230

---

src/main/webapp/json/variableDatasetMapping.json

I used the var major code for snow water equivalent... not sure that will work?
See table 3: http://www.rcc-acis.org/docs_webservices.html for what I mean by var major.

adding more variables to the variableDatasetMapping

---

src/main/webapp/Intro.jsp
src/main/webapp/WEB-INF/jsp/head.jsp
src/main/webapp/dataDiscovery.jsp
src/main/webapp/js/hb_templates/aoiBox.hbs
src/main/webapp/js/hb_templates/choose.hbs
src/main/webapp/js/hb_templates/chooseByVariable.hbs
src/main/webapp/js/hb_templates/dataDiscovery.hbs
src/main/webapp/js/hb_templates/location.hbs
src/main/webapp/js/hb_templates/processData.hbs
src/main/webapp/js/hb_templates/workflowNav.hbs
src/main/webapp/js/views/AOIBoxView.js
src/main/webapp/js/views/ChooseByVariableKindView.js
src/main/webapp/js/views/ChooseView.js
src/main/webapp/js/views/LocationView.js

Still in process, just putting this PR out there so y'all know what I'm up to.

Text changes.

---

pom.xml
src/main/webapp/Intro.jsp
src/main/webapp/WEB-INF/jsp/head.jsp

A couple changes to headings to reflect the expansion to more than great lakes beaches.

upping to new shapefile uploader

---

src/main/webapp/WEB-INF/jsp/sidebar.jsp

I changed to 'Time Series' to be consistent with the labels in the rest of the app.

Added EC to Data Sources and Partners

---

src/main/webapp/Intro.jsp
src/main/webapp/UserGuide.jsp
src/main/webapp/WEB-INF/jsp/head.jsp
src/main/webapp/WEB-INF/jsp/header.jsp

I am pretty sure this is correct, but please review content and code of course.

Added filter file formats to the user guide.

---

src/main/webapp/WEB-INF/jsp/sidebar.jsp
src/main/webapp/WEB-INF/jsp/statusHead.jsp
src/main/webapp/WEB-INF/web.xml
src/main/webapp/js/serviceStatusOnReady.js
src/main/webapp/serviceStatus.jsp

Using JNDI parameters to provide the URL matching used when parsing the enddat_external_services_monitoring log and to map a service name to a urlmatch. The location of the data directory containing the log will be defined with a resource in context.xml.

Enddat 267 - Create Web Service Status Page
